### ISSUE TITLE
Active development

### ISSUE THREAD

**Issue by RichardLitt** [contribute-md/contribute-md-template#5]
Hey @hone and @lindaliukas. Are you guys still interested in maintaining this project? 

There's been a few issues open for a while, and no change to the template file in over a year. I just tried to use contribute.md and had some issues adapting it to my project; I'd like to address those issues here, or at least see this project go forward, but I'm not sure if either of you are still interested in maintaining this organization. Figured I'd ask. :) 

If not, it'd be great if we could coordinate with [jden/CONTRIBUTING.md](https://github.com/jden/CONTRIBUTING.md), as he's doing a very similar thing to this project.

**Comment by hone** [comment]
Hi @RichardLitt. I'm really bad at github notifications, but trying to fix that now. Yeah, after github announced [contributing.md](https://github.com/blog/1184-contributing-guidelines), this project kind of lost steam. I'd be happy to help or coordinate with people who want to be active!

**Comment by RichardLitt** [comment]
Makes sense. GitHub doesn't suggest a contributing.md file, though, although they give a few examples. A repository that has templates would still be useful if it could gain traction, I think.

**Comment by hone** [comment]
Yeah, I think so too. Should I add you to the org or should we shut this
down?

**Comment by RichardLitt** [comment]
Well, at the moment I don't think that they are really going for being a template for CONTRIBUTE docs. I think that this repo, then, has enough going for it to continue being useful, as long as some work was put into it and the marketing was kept up - talking about it on GitHub, pulling CONTRIBUTE files from various open source projects and taking what we can here, etc. etc. The worst thing that can happen is to just let this go stale (which I think has been happening). 

Another branch that we should look into, as far as active development, is looking at [this issue on standard](https://github.com/feross/standard/issues/141) by about having a standard checker for READMEs for node packages, which is now live in [this repo](https://github.com/zcei/standard-readme). We could potentially make a standard-contribute checker, which would be good - and, in that case, it'd be great to have a list of examples like we have here, or one example to check against. So, I think there's still work to do helping communities which isn't being done, and we can do that. 

I can help with some of this. I'd be happy to start doing small PRs and stuff here and there, and to be in the organization.

**Comment by hone** [comment]
That sounds great. The checker seems really interesting. I added you to the
org. I'm going to close this issue.

**Comment by RichardLitt** [comment]
Thanks! Ok, I'll see what I can do to get this started again.
